In [3]:
import pandas as pd
from sklearn.datasets import load_iris

In [41]:
data = load_iris()
df = pd.DataFrame(data.data)
columns = ["sepal_length", "sepal_width", "petal_length", "petal_width"]
df.columns  = columns

In [35]:
cov_mat = [
    df.sepal_length.cov(df.sepal_width),
    df.sepal_length.cov(df.petal_length),
    df.sepal_length.cov(df.petal_width),
]

cor_mat = [
    df.sepal_length.corr(df.sepal_width),
    df.sepal_length.corr(df.petal_length),
    df.sepal_length.corr(df.petal_width),
]

cov_mat, cor_mat

([np.float64(-0.042434004474272924),
  np.float64(1.2743154362416111),
  np.float64(0.516270693512304)],
 [np.float64(-0.11756978413300208),
  np.float64(0.8717537758865831),
  np.float64(0.8179411262715757)])

In [38]:
mean_mat = [
    df.sepal_length.mean(),
    df.sepal_width.mean(),
    df.petal_length.mean(),
    df.petal_width.mean(),
]

std_mat = [
    df.sepal_length.std(),
    df.sepal_width.std(),
    df.petal_length.std(),
    df.petal_width.std(),
]

mean_mat, std_mat

([np.float64(5.843333333333334),
  np.float64(3.0573333333333337),
  np.float64(3.7580000000000005),
  np.float64(1.1993333333333336)],
 [0.8280661279778629,
  0.435866284936698,
  1.7652982332594667,
  0.7622376689603465])

In [44]:
df.describe().loc["mean",  columns]

sepal_length    5.843333
sepal_width     3.057333
petal_length    3.758000
petal_width     1.199333
Name: mean, dtype: float64

In [45]:
df.describe().loc["std",  columns]

sepal_length    0.828066
sepal_width     0.435866
petal_length    1.765298
petal_width     0.762238
Name: std, dtype: float64

In [49]:
df.loc[[0, 1]]

   sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2